### ISSUE TITLE
Registered CPT meta boxes not saving

### ISSUE THREAD

**Issue by ryans1224** [victoraigbeghian/WP-Plugin-Starter-Kit#2]
Fresh install & gulp run - The example meta boxes (see screenshot below) do not save their data when the CPT entry is saved. 

![image](https://user-images.githubusercontent.com/7398104/75968907-0c3bc280-5ec6-11ea-8864-5c60d3367b8e.png)

**Comment by victoraigbeghian** [comment]
Meta box class has been updated.
